name: Building, testing and packaging

on: workflow_dispatch
  #push:
    #branches:
      #- main  
  #pull_request:
    #branches:
      #- main  

jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Makefile
        run: |
          cd ./cicd
          make 
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: | 
            ./bin
            Test

  run-test:
    runs-on: ubuntu-latest
    needs: run-make  
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
      - name: Make test executable
        run: chmod +x ./build/bin/Test
      - name: Run test
        id: test
        run: |
          cd ./build
          ./bin/Test
          if [ $? -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

  run-packaging:
    runs-on: ubuntu-latest
    needs: run-test  
    if: needs.run-test.outputs.status == 'success'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
      - name: Create .deb package
        run: |
          mkdir -p BubbleSort/DEBIAN
          mkdir -p BubbleSort/usr/bin
          cp -r ./build/bin BubbleSort/usr/bin
          echo "Package: BubbleSort" > BubbleSort/DEBIAN/control
          echo "Version: 1.0" >> BubbleSort/DEBIAN/control
          echo "Section: utils" >> BubbleSort/DEBIAN/control
          echo "Priority: optional" >> BubbleSort/DEBIAN/control
          echo "Architecture: all" >> BubbleSort/DEBIAN/control
          echo "Maintainer: Ya" >> BubbleSort/DEBIAN/control
          echo "Description: BubbleSort" >> BubbleSort/DEBIAN/control
          dpkg-deb --build BubbleSort
        #mv BubbleSort.deb ./cicd

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: BubbleSort.deb
